spring.application.name=swapxride-api

# Database Configuration (Supabase PostgreSQL)
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0&sslmode=require
spring.datasource.username=postgres.ocqjktjtoissltwkyvdc
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=password
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.show-sql=true

# JWT Secret
jwt.secret=${JWT_SECRET:your_super_secret_key_change_in_production}
jwt.expiration=86400000

# File Upload (Multipart)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Initial Data Loading
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update

# Stripe Configuration
stripe.api.key=${STRIPE_API_KEY}
