package com.carswap.backend.config;

import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@RequiredArgsConstructor
public class SchemaFixer {

    private final JdbcTemplate jdbcTemplate;

    @PostConstruct
    public void fixSchema() {
        System.out.println("Running SchemaFixer to correct message foreign keys...");
        try {
            // 1. Drop the specific incorrect Hibernate-generated constraint for
            // recipient_id if it exists
            // The name is taken from the logs: fkhdkwfnspwb3s60j27vpg0rpg6
            try {
                jdbcTemplate.execute("ALTER TABLE messages DROP CONSTRAINT IF EXISTS fkhdkwfnspwb3s60j27vpg0rpg6");
                System.out.println("Dropped constraint fkhdkwfnspwb3s60j27vpg0rpg6");
            } catch (Exception e) {
                System.out.println(
                        "Constraint fkhdkwfnspwb3s60j27vpg0rpg6 might not exist or failed to drop: " + e.getMessage());
            }

            // 2. Identify and drop any other FKs on messages that reference 'users' table
            // This handles the sender_id constraint and dynamic names
            String findConstraintsSql = "SELECT con.conname " +
                    "FROM pg_constraint con " +
                    "JOIN pg_class rel ON rel.oid = con.conrelid " +
                    "JOIN pg_class ref ON ref.oid = con.confrelid " +
                    "WHERE rel.relname = 'messages' " +
                    "AND ref.relname = 'users' " + // Target is 'users' (bad)
                    "AND con.contype = 'f'";

            List<String> badConstraints = jdbcTemplate.queryForList(findConstraintsSql, String.class);

            for (String constraintName : badConstraints) {
                System.out.println("Dropping bad constraint: " + constraintName);
                jdbcTemplate.execute("ALTER TABLE messages DROP CONSTRAINT " + constraintName);
            }

            // 3. Add correct constraints referencing 'profiles'
            // We use specific names to avoid duplication
            addConstraintIfNotExists("fk_messages_recipient_profiles",
                    "ALTER TABLE messages ADD CONSTRAINT fk_messages_recipient_profiles FOREIGN KEY (recipient_id) REFERENCES profiles(id) ON DELETE CASCADE");

            addConstraintIfNotExists("fk_messages_sender_profiles",
                    "ALTER TABLE messages ADD CONSTRAINT fk_messages_sender_profiles FOREIGN KEY (sender_id) REFERENCES profiles(id) ON DELETE CASCADE");

            // 4. Fix Listing Status Check Constraint
            // The default Hibernate generated constraint might rely on an old ENUM
            // definition or be missing values.
            // We will drop the check constraint and re-add it with all valid values.
            try {
                // Drop the constraint if it exists (it might have a different name generated by
                // Hibernate,
                // but the error logs said "listings_status_check")
                jdbcTemplate.execute("ALTER TABLE listings DROP CONSTRAINT IF EXISTS listings_status_check");
                System.out.println("Dropped constraint listings_status_check");

                // Add the correct constraint
                jdbcTemplate.execute("ALTER TABLE listings ADD CONSTRAINT listings_status_check " +
                        "CHECK (status IN ('active', 'sold', 'expired', 'deleted', 'pending_payment'))");
                System.out.println("Added updated listings_status_check constraint");
            } catch (Exception e) {
                System.err.println("Failed to update listings_status_check: " + e.getMessage());
            }

            System.out.println("SchemaFixer completed successfully.");

        } catch (Exception e) {
            System.err.println("SchemaFixer failed: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void addConstraintIfNotExists(String constraintName, String ddl) {
        String checkSql = "SELECT count(*) FROM pg_constraint WHERE conname = ?";
        Integer count = jdbcTemplate.queryForObject(checkSql, Integer.class, constraintName);
        if (count == null || count == 0) {
            System.out.println("Adding constraint: " + constraintName);
            jdbcTemplate.execute(ddl);
        } else {
            System.out.println("Constraint " + constraintName + " already exists.");
        }
    }
}
